CREATE TABLE ticket_messages (
                                 message_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 ticket_id       NUMBER NOT NULL,
                                 sender_role     VARCHAR2(10) CHECK (sender_role IN ('USER', 'ADMIN')) NOT NULL,
                                 sender_id       VARCHAR2(255) NOT NULL,
                                 message_text    CLOB NOT NULL,
                                 creation_date   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 update_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE ticket_messages
    ADD CONSTRAINT fk_ticket_messages_ticket_id
        FOREIGN KEY (ticket_id)
            REFERENCES tickets(ticket_id);

CREATE OR REPLACE TRIGGER trg_ticket_messages_update
BEFORE UPDATE ON ticket_messages
                  FOR EACH ROW
BEGIN
    :NEW.update_date := CURRENT_TIMESTAMP;
END;
/

ALTER TRIGGER trg_ticket_messages_update ENABLE;